Make use of CoordinateFrame.reference_frame
spacetelescope/gwcs pull request #365
Opened 2021-05-13 19:51 UTC by dstansby

If `CoordinateFrame` has a `reference_frame` attached, use it to return a `SkyCoord` object from `CoordinateFrame.coordiantes`. This is similar to the way `CelestialFrame` works, and I think the right way to allow definition of a general `CoordinateFrame` that still returns a `SkyCoord`.

2021-05-14 08:59 UTC, Cadair requested changes
The base CoordinateFrame class isn't where this should be, if you have a SklyCoord coord you need `CelestialFrame`. Which probably means you need to fix #120

2021-05-14 10:51 UTC, nden commented
@dstansby Could you describe your use case?

2021-05-14 17:11 UTC, dstansby commented
I'm trying to construct a WCS for the output of a magnetic field model of the Sun, which is defined on a 3D grid in (latitude, longitude, radius). This means I want `wcs.pixel_to_world()` to return coordinates in a `sunpy.coordinates.HeliographicCarrington` frame, which I assumed wasn't a celestial frame.

Should any wcs that transforms to a `SkyCoord` be using `CelestialFrame` then? If so I think some clarification in the docs on the distinction between `CoordinateFrame` and `CelestialFrame` would be good.

2021-05-14 21:48 UTC, Cadair commented
> Should any wcs that transforms to a SkyCoord be using CelestialFrame then? 

From a practical perspective with how the APE 14 interface is implemented. Yes.

2021-05-15 09:03 UTC, dstansby commented
> > Should any wcs that transforms to a SkyCoord be using CelestialFrame then?
> 
> From a practical perspective with how the APE 14 interface is implemented. Yes. To make it work with your use case, you would need to fix #120.

Can you expand a bit more? `CelestialFrame` seems pretty hard coded to deal with 2D frames where the two axes are latitude and longitude, which is what I would say defines a frame as being celestial. If `CoordinateFrame` isn't designed to return a `SkyCoord` (which judging by `_world_axis_object_classes` it indeed isn't), maybe a new class for returning an arbitrary `SkyCoord` (as opposed to being limited to celestial frames) should be created?

2021-05-15 11:34 UTC, Cadair commented
`CelestialFrame` is the one which describes itself with a SkyCoord. I personally don't see the need to add another frame when one could generalise `CelestialFrame` to be "anything which goes in a SkyCoord". Unless @nden has other reasons.

2021-05-15 12:16 UTC, nden commented
I agree with @Cadair . 
There are two issues - the CelestialFrame definition and the serialization.
For the first one try adding `naxes` to `CelestialFrame.__init__`. 

It would be helpful to have a code snippet which shows the problem and the expectation.

2021-05-15 12:31 UTC, dstansby commented
Thanks for taking the time to explain since I'm new to all this 😄  I shall close this in favour of https://github.com/spacetelescope/gwcs/issues/120, and also open an issue with my current `WCS` construction and expected output.

2021-05-15 12:31 UTC, closed without merging