fix deprecation warning when wcs is initialized with a pipeline
spacetelescope/gwcs pull request #368
Opened 2021-06-08 12:40 UTC by cshanahan1

fixes https://github.com/spacetelescope/gwcs/issues/361

2021-06-21 22:46 UTC, jdavies-st approved these changes
Looks good.  Fixes the warning we're seeing in `jwst`.

You'll want to add a small test that runs the code through the `else` blocks and does something like:

```python
with pytest.warns(DeprecationWarning, match="Indexing a WCS.pipeline step is deprecated"):
    do stuff that goes through the else block
```

or similar.

2021-07-02 13:43 UTC, cshanahan1 commented
It wasn't a problem with initializing a wcs with a list of tuples of (frame, transform) - it happened because there were wcs.Step() items in the forward_transform list the wcs was being initialized with which gave that warning when trying to index them rather than accessing their .frame and .transform attributes. 

I also used `pytest.mark.filterwarnings` to declare that particular warning as an error and fail the test if it appears, it looks like the pytest.warns example above is useful to ensure a warning DOES occur?

2021-07-02 18:30 UTC, jdavies-st commented
Looks great! And thanks for the clarification.  I added that text to the top of the PR.  Just add an entry to CHANGES.rst and we can merge.

2021-07-13 13:49 UTC, nden requested changes

2021-07-13 13:49 UTC, nden commented on gwcs/tests/test_wcs.py
> +    pipeline.append(extra_step)
This test creates the pipeline incorrectly. The `None` sentinel must be in the last step. The errors is currently raised only when the WCS is printed or executed. There should be a check in the initialization of the WCS.

2021-07-13 13:49 UTC, nden commented on gwcs/wcs.py
> +        self._pipeline = pipe
This code may be moved to the `_initialize_wcs` function.

2021-07-13 13:51 UTC, nden commented
It doesn't solve the issue completely, gwcs tests (specifically test_get_transfrom) still raise the warning.
I think it's the right approach but needs more work.

2021-07-19 17:51 UTC, cshanahan1 commented
@nden the reason that test_get_transform was raising the warning was because it was testing that indexing a pipeline step works the same as accessing the transform attribute
`    assert_allclose(w.pipeline[0].transform(x, y), (fx, fy))`
`    assert_allclose(w.pipeline[0][1](x, y), (fx, fy))`

If it's actually being deprecated, should that second line just be removed from the tests? Or is the issue that indexing a step shouldn't raise a deprecation warning at all anymore, because right now that warning is in getitem for Step.

2021-07-19 17:56 UTC, cshanahan1 commented
And similarly, the tests in test_init_no_transform() are testing because they're comparing 

` pipeline[0][0]`
to
`pipeline[0].frame` 

etc, which is obviously raising that warning because that's trying to index a step. The fix I put here was indexing of steps that was happening internally which is not fixed, whereas this is indexing that is explicitly written in a test.

2021-08-28 23:21 UTC, nden commented
Needs a rebase and please fix a code style issue [here](https://github.com/spacetelescope/gwcs/runs/3452321810?check_suite_focus=true). I merged the other PR with the error.

2021-08-28 23:22 UTC, nden commented on gwcs/tests/test_wcs.py
> +    pipeline = [('detector', trans), ('sky', None)]
Only the last step in a pipeline can have a transform `None`.

2021-09-02 15:41 UTC, jdavies-st commented
> Needs a rebase and please fix a code style issue [here](https://github.com/spacetelescope/gwcs/runs/3452321810?check_suite_focus=true). I merged the other PR with the error.

I fixed the code style error in #372.

2021-11-16 22:06 UTC, nden approved these changes

2021-11-16 23:22 UTC, merged